### ISSUE TITLE
Document development workflow

### ISSUE THREAD

**Issue by invidian** [gardener/gardener-extension-provider-packet#109]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement
/priority normal
/platform equinix-metal

**What would you like to be added**:

There should be a documentation added, how to setup Gardener from scratch, what are the constraints while doing so and finally how to build and use development image of this extension.

**Why is this needed**:

There should be well-defined set of steps one can follow to contribute to this project.

**Comment by rfranzke** [comment]
@deitch can this issue be closed now that you updated https://github.com/gardener/gardener-extension-provider-packet/blob/master/CONTRIBUTING.md?

**Comment by deitch** [comment]
definitely!
